packages: []

catalogs:
  build:
    '@sveltejs/adapter-auto': ^6.1.0
    '@sveltejs/kit': ^2.37.0
    '@sveltejs/package': ^2.5.0
    '@sveltejs/vite-plugin-svelte': ^6.1.4
    vite: ^7.1.4
  dev:
    '@antfu/eslint-config': ^5.2.2
    eslint: ^9.34.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-svelte: ^3.12.1
    publint: ^0.3.12
    svelte-check: ^4.3.1
    typescript: ^5.9.2
  frontend:
    motion-dom: ^12.23.12
    motion-utils: ^12.23.6
    svelte: ^5.38.7

onlyBuiltDependencies:
  - esbuild
